#####
name: Blackduck_Scans

on:
  push:
    branches: [ main, master]
  pull_request:
    branches: [ main, master]
  workflow_dispatch:  
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@v1.8.0
        ### Use below configurations to set specific detect environment varibales
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          #DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          #DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
        with:
          #bridge_download_url: https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-bridge/1.2.0/synopsys-bridge-1.2.0-linux64.zip
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
          #blackduck_scan_full: true
          ### Accepts Multiple Values
          #blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          ### Uncomment below configuration to enable autoamtic fix pull request creation if vulnerabilities are reported
          #blackduck_fixpr_enabled: true
          #blackduck_fixpr_maxCount: 3
          #blackduck_fixpr_filter_severities: "MEDIUM,LOW"
          #blackduck_fixpr_useUpgradeGuidance: "LONG_TERM,SHORT_TERM"
          blackduck_reports_sarif_create: true
          blackduck_upload_sarif_report: true
          github_token: ${{ secrets.GIT_PAT_TOKEN }} # Mandatory when blackduck_automation_fixpr is set to 'true'
          ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
          #include_diagnostics: true 
